name: "DecisionTree Machine Learning Deploy Action"
description: "Deploy a registered model in your DecisionTree Machine Learning Workspace with this GitHub Action"
inputs:
  model_name:
    description: "Name of the model that will be deployed"
    required: true
  model_version:
    description: "Version of the model that will be deployed"
    required: true
outputs:
  service_scoring_uri:
    description: "Scoring URI of the webservice that was created (only provided if delete_service_after_deployment is set to False)"
  service_swagger_uri:
    description: "Swagger URI of the webservice that was created (only provided if delete_service_after_deployment is set to False)"
runs:
  using: "docker"
  image: "Dockerfile"
