name: Pull request labeler
on: [ pull_request_target ]

permissions:
  contents: read
  pull-requests: write

jobs:
  pycheck:
    uses: ./.github/workflows/workflow1.yml@master
    secrets:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  get-env:
    needs:[pycheck]
    uses: ./.github/workflows/git-hub-action-demo.yml@master
    secrets:
    
