name: Reusable workflow example

on:
  workflow_call:
#     inputs:
#       username:
#         description: 'A username passed from the caller workflow'
#         default: 'john-doe'
#         required: false
#         type: string

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print name 
        uses: ./.github/workflows/workflow1.yml
