name: Reusable workflow example

on:
  workflow_call:
#     inputs:
#       username:
#         required: true
#         type: string
#     secrets:
#       token:
#         required: true

jobs:
  example_job:
    name: Use workflow1
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/workflow1.yml@v1
