name: test github action
on: [push]
#   workflow_run:
#     workflows: [GitHub Actions Demo]
#     types:
#       - completed
#   workflow_dispatch:
#     inputs:
#       name:
#         description: 'CI Number'
#         required: true
#   push:
#     branches:
#      - master
jobs:
  job1:
    uses: ./.github/workflows/workflow-1.yml
  train:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    
      - name: Runing Success
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo 'The workflow passed'
        
      - name: Run Failure
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: echo 'The workflow failed'
